version: '3.8'

services:
  game:
    build:
      context: .
      dockerfile: Dockerfile.game
    ports:
      - '3000:80' # Map port 3000 on the host to port 80 in the container
    environment:
      - NODE_ENV=development
    command: 'pnpm dev'
    restart: always

  storybook:
    build:
      context: .
      dockerfile: Dockerfile.storybook
      target: development
    ports:
      - '6006:6006'
    volumes:
      # Mount source code for hot reloading
      - ./src:/app/src:ro
      - ./.storybook:/app/.storybook:ro
      # Mount other common directories that might affect Storybook
      - ./public:/app/public:ro
      - ./stories:/app/stories:ro
      # Preserve node_modules (don't mount from host)
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true # Better file watching in Docker
      - WATCHPACK_POLLING=true # Alternative polling option
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - storybook-network

networks:
  storybook-network:
    driver: bridge
