version: '3.8'

services:
  game:
    build:
      context: .
      dockerfile: Dockerfile.game
    ports:
      - '3000:3000'
    volumes:
      - .:/game
      - /game/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

  storybook:
    build:
      context: .
      dockerfile: Dockerfile.storybook
    ports:
      - '6006:6006'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
