FROM node:22-alpine

WORKDIR /game

COPY package*.json ./
COPY pnpm-lock.yaml ./

RUN npm i pnpm -g
RUN pnpm i --frozen-lockfile --ignore-scripts

COPY . .

EXPOSE 3000

CMD ["pnpm", "run", "dev", "--", "--host", "0.0.0.0"]